version: '2.0'
services:
  web:
    image: my_site
    container_name: wbsr
    ports:
        - 8090:80
        - 3309:3306
    volumes:
      - ./core/www:/var/www/site
      - ./core/:  /var/lib/mysql
     
    environment: 
      MYSQL_ROOT_PASSWORD: bob
      MYSQL_DATABASE: bob
      MYSQL_USER: bob
      MYSQL_PASSWORD: bobpassw
